### ISSUE TITLE
Reason for having dedicated provider classes ?

### ISSUE THREAD

**Issue by ksachdeva** [driftyco/ionic-paging-animation-app#1]
Hi Dan,

Was going through the various files in util folder related to Gestures and could not understand the significance and value of having provider classes. At present these provider classes are simply wrapping the respective gesture classes.

You should be able to put Injectable() on the gesture class itself.

Most likely missing the use case and reason

Please educate

Regards & thanks
Kapil

**Comment by danbucholtz** [comment]
Hi @ksachdeva,

We're looking into that.  I went ahead and removed the gesture classes as they snuck into this app via and copy and paste error.  Thanks for checking out the project and for the tip!

Thanks,
Dan

**Comment by yozman** [comment]
@danbucholtz
which dribbble is this?
could u plz tell me?
