### ISSUE TITLE
Cannot find module '@angular/forms'

### ISSUE THREAD

**Issue by karvannan-thi** [driftyco/ionic-paging-animation-app#2]
after install npm getting this error when i run this app

**Comment by danbucholtz** [comment]
Hi @karvannan-thi,

I fixed the `package.json` to rely on ionic 2 beta 10, instead of what will be beta 11.  The `@angular/forms` module is new in what will become beta 11.

Thanks,
Dan

**Comment by yozman** [comment]
@danbucholtz 
which dribbble is this?
could u plz tell me?
